# Site Settings
title: WeTry | Just another dev blog
email: info@wetry.tech
description: Just another dev blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wetry.tech" # the base hostname & protocol for your site
google_analytics: "UA-145445435-1"

# User Settings
username: WeTry
user_description: Some text about you.
disqus_username: wetry

# Social Media
# Remove the item if you don't need it
github_username: wetryio
# facebook_username: facebook_username
# twitter_username: twitter_username
# instagram_username: instagram_username
# linkedin_username: linkedin_username
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: HITW 2019
    url: /hitw2019/
  - title: About
    url: /about/
  - title: CraftLabIT
    url: /craftlab-it/
  # - title: Contact
  #   url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
